apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "400M", "--timeout", "300s"]